#!/bin/bash

#

#PBS -N bowtie2_Control_k40-soapTrans.okay           

#PBS -A UQ-account

#PBS -l nodes=1:ppn=10:intel,mem=50GB,walltime=36:00:00



module load bowtie2/2.2.7

module load samtools/1.3


bowtie2 -p10 -k40 -x /home/studentID/ycs/bowtie2_indexes/soapTrans.okay -1 /30days/studentID/concat_trimreads/Control_1.fq -2 /30days/studentID/concat_trimreads/Control_2.fq | samtools view -Sbh -o /30days/studentID/Control-soapTrans.okay-multi_aligned.bam

