#!/bin/bash

#

#PBS -N bowtie2_YCS_k40-velvet.okay           

#PBS -A UQ-account

#PBS -l nodes=1:ppn=10:intel,mem=50GB,walltime=24:00:00

#PBS -m ea


module load bowtie2/2.2.7

module load samtools/1.3


bowtie2 -p10 -k40 -x /home/studentID/ycs/bowtie2_indexes/velvet.okay -1 /30days/studentID/concat_trimreads/YCS_1.fq -2 /30days/studentID/concat_trimreads/YCS_2.fq | samtools view -Sbh -o /30days/studentID/YCS-velvet.okay-multi_aligned.bam

